Repository webanno/webanno, pull requests merged in 2018-04, with the labels that each got.

#907 #792 - Webhook for status change notification
  webanno-remote/pom.xml
Labels: Remote API, bug

#910 #909 - Update checkstyle (again)
  pom.xml
Labels: Refactoring

#913 Feature/862 modularize documentation
  webanno-diag/src/main/resources/META-INF/asciidoc/developer-guide/casdoctor.adoc
  webanno-ui-project/src/main/resources/META-INF/asciidoc/user-guide/projects.adoc
Labels: Documentation

#915 Add Ajax Event in AnnotationDetailEditorPanel
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/event/AjaxAfterAnnotationUpdateEvent.java
Labels: enhancement

#919 #898 - Allow feature-type specific configurations
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/SlotFeatureSupport.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureTraitsEditor.html
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureTraitsEditor.java
Labels: Refactoring

#925 #924 - Renaming layer is not working
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.java
Labels: Module: Settings, 🐛Bug

#920 #918 - Link feature trait for default slots
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/AnnotationSchemaService.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/SlotFeatureSupport.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureEditor.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureTraits.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureTraitsEditor.html
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureTraitsEditor.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java
Labels: Module: Annotation, Module: Settings, 🆕Enhancement
