Repository webanno/webanno, pull requests merged in 2018-07, with the labels that each got.

#1013 #974 - Upgrade dependencies
  pom.xml
  webanno-api-automation/pom.xml
  webanno-api-dao/pom.xml
  webanno-api/pom.xml
  webanno-automation/pom.xml
  webanno-constraints/pom.xml
  webanno-curation/pom.xml
  webanno-model-export/pom.xml
  webanno-model/pom.xml
  webanno-project/pom.xml
  webanno-remote/pom.xml
  webanno-security/pom.xml
  webanno-support/pom.xml
  webanno-ui-annotation/pom.xml
  webanno-ui-automation/pom.xml
  webanno-ui-project/pom.xml
Labels: ⚙️Refactoring

#1012 Bugfix/1011 error calculating project state
  webanno-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
Labels: 🐛Bug

#1014 #892 - Do not load the project page if the user does not have the proper rights
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.java
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/menu/MenuItemRegistry.java
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/menu/MenuItemRegistryImpl.java
Labels: 🐛Bug

#1015 #783 - Color of a layer changes depending on how many layers are enabled
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratRenderer.java
Labels: Module: Annotation, 🐛Bug

#1016 #896 - Handle case where imported XMI file does not contain DocumentMetaData
  webanno-brat/pom.xml
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/util/BratAnnotatorUtility.java
  webanno-brat/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/util/BratAnnotatorUtilityTest.java
  webanno-ui-correction/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/correction/CorrectionPage.java
Labels: 🐛Bug

#1018 #1017 - Improve "open document" dialog
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/dialog/OpenDocumentDialogPanel.java
Labels: Module: Annotation, 🆕Enhancement

#1019 #816 - Refreshing the curation page doesn't result in correct state after changing state in API
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/util/BratAnnotatorUtility.java
Labels: Module: Curation, 🐛Bug

#1025 #1024 - Create AnnotationDocument for user when using readAnnotationCas
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java
  webanno-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImplTest.java
  webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentService.java
Labels: ⚙️Refactoring

#1027 #1026 - Upgrade to recent MySQL driver
  webanno-webapp/pom.xml
Labels: 🆕Enhancement
