Repository webanno/webanno, pull requests merged in 2018-12, with the labels that each got.

#1145 Bugfix/1144 scope brat styles to brat visualization
  webanno-brat/pom.xml
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.html
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratVisualizer.html
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/BratCssUiReference.java
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/BratCssVisReference.java
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/style-ui.css
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/style-ui.less
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/style-vis.css
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/style-vis.less
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/CurationPanel.java
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/model/BratSuggestionVisualizer.html
Labels: Module: Annotation, 🐛Bug

#1147 #1146 - Make it possible to list all <SourceDocument, AnnotationDocument> pairs
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java
  webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentService.java
Labels: 🆕Enhancement

#1149 #1148 - Add method to read JSON from InputStream
  webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/JSONUtil.java
Labels: 🆕Enhancement

#1151 #1150 - Avoid passing AnnotatorState to TypeAdapter
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/ArcAdapter.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/AutomationTypeAdapter.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/ChainAdapter.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/SpanAdapter.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter_ImplBase.java
  webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/util/AutomationUtil.java
Labels: ⚙️Refactoring

#1159 Feature/1150 avoid passing annotator state to type adapter
  pom.xml
  webanno-api-annotation/pom.xml
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/AutomationTypeAdapter.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/SpanAdapter.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter_ImplBase.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/event/FeatureValueUpdatedEvent.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/event/SpanCreatedEvent.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/event/SpanDeletedEvent.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/model/VAnnotationMarker.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/model/VMarker.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/model/VSentenceMarker.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/model/VTextMarker.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasMetadataUtils.java
  webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/event/AfterDocumentResetEvent.java
  webanno-fontawesome/LICENSE.txt
  webanno-fontawesome/NOTICE.txt
  webanno-fontawesome/marker-wicket-module
  webanno-fontawesome/pom.xml
  webanno-fontawesome/src/main/java/de/tudarmstadt/ukp/clarin/webanno/fontawesome/FontAwesomeCssReference.java
  webanno-fontawesome/src/main/java/de/tudarmstadt/ukp/clarin/webanno/fontawesome/css/font-awesome.css
  webanno-fontawesome/src/main/java/de/tudarmstadt/ukp/clarin/webanno/fontawesome/css/font-awesome.min.css
  webanno-fontawesome/src/main/java/de/tudarmstadt/ukp/clarin/webanno/fontawesome/fonts/FontAwesome.otf
  webanno-fontawesome/src/main/java/de/tudarmstadt/ukp/clarin/webanno/fontawesome/fonts/fontawesome-webfont.eot
  webanno-fontawesome/src/main/java/de/tudarmstadt/ukp/clarin/webanno/fontawesome/fonts/fontawesome-webfont.svg
  webanno-fontawesome/src/main/java/de/tudarmstadt/ukp/clarin/webanno/fontawesome/fonts/fontawesome-webfont.ttf
  webanno-fontawesome/src/main/java/de/tudarmstadt/ukp/clarin/webanno/fontawesome/fonts/fontawesome-webfont.woff
  webanno-fontawesome/src/main/java/de/tudarmstadt/ukp/clarin/webanno/fontawesome/fonts/fontawesome-webfont.woff2
  webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/event/HybridApplicationUIEvent.java
  webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/event/HybridApplicationUIEventRouter.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPageBase.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.html
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationFeatureForm.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/AnnotationSidebar_ImplBase.java
  webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/page/AutomationPage.java
  webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/util/AutomationUtil.java
  webanno-ui-core/pom.xml
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/config/FontAwesomeResourceBehavior.java
  webanno-ui-correction/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/correction/CorrectionPage.java
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/CurationPanel.java
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/util/MergeCas.java
Labels: 🆕Enhancement

#1171 #1170 - Reorganize behavior code
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/ArcAdapter.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/CreateRelationAnnotationRequest.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/CreateSpanAnnotationRequest.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/SpanAdapter.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/layer/RelationLayerSupport.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
  webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/util/AutomationUtil.java
  webanno-ui-curation/pom.xml
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/util/MergeCas.java
  webanno-ui-curation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/util/CopyAnnotationTest.java
Labels: Module: Annotation, ⚙️Refactoring
