Repository webanno/webanno, pull requests merged in 2018-03, with the labels that each got.

#880 #879 Unable to delete automation project
  webanno-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/automation/service/AutomationServiceEventAdapter.java
Labels: Automation, bug

#882 #881 Use stable order in left side bar
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/AnnotationSidebarRegistryImpl.java
Labels: bug

#891 #890 - listAccessibleProjects should include projects in which the user is an annotator or curator
  webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/ProjectService.java
  webanno-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectSelectionPanel.java
Labels: enhancement
