Repository webanno/webanno, pull requests merged in 2018-02, with the labels that each got.

#847 #846 - Layer Settings: Feature selected but details not shown
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.java
Labels: Settings, bug

#845 Trigger LayerConfigurationChangedEvent after any changes to layers or features
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.java
Labels: enhancement

#849 #827 - Error pressing save directly after import
  pom.xml
  webanno-api-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/automation/model/AutomationStatus.java
  webanno-api-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/automation/model/MiraTemplate.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java
  webanno-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/automation/service/MiraAutomationServiceImpl.java
  webanno-brat/pom.xml
  webanno-brat/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/ajax/controller/CasToBratJsonTest.java
  webanno-brat/src/test/resources/output_cas_to_json_document_expected.json
  webanno-export/src/main/java/de/tudarmstadt/ukp/clarin/webanno/export/ExportServiceImpl.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationDocument.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationFeature.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationLayer.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/ConstraintSet.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/PermissionLevel.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/PermissionLevelType.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/Project.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/ProjectPermission.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/SourceDocument.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/Tag.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/TagSet.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/TrainingDocument.java
  webanno-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
  webanno-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/WebhookServiceTest.java
  webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/model/Authority.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationFeatureForm.java
  webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/project/ProjectMiraTemplatePanel.java
  webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/project/ProjectTrainingDocumentsPanel.java
  webanno-ui-monitoring/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/monitoring/page/MonitoringPage.java
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectPage.java
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/constraints/ProjectConstraintsPanel.java
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/detail/ProjectDetailPanel.java
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/ImportDocumentsPanel.java
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/guidelines/ImportGuidelinesPanel.java
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.java
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/tagsets/ProjectTagSetsPanel.java
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/tagsets/TagEditorPanel.java
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/tagsets/TagSetEditorPanel.java
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/tagsets/TagSetImportPanel.java
Labels: bug

#843 #842 - Extend forward annotation to a feature without a tagset
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/action/AnnotationActionHandler.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.html
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationFeatureForm.java
Labels: Annotation, enhancement
