Repository webanno/webanno, pull requests merged in 2019-03, with the labels that each got.

#1246 #1244 - webanno-ui-core should not hard-depend on webanno-remote
  webanno-ui-core/pom.xml
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/ManageUsersPage.java
Labels: ⚙️Refactoring

#1248 #1247 - Upgrade dependencies (3.6.0)
  pom.xml
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/Select2TextFeatureEditor.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/TextFeatureEditorBase.java
Labels: ⚙️Refactoring

#1245 #1243 - UIMA TS using built-in type as slot filler cannot be reimported
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/AnnotationSchemaService.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/PrimitiveUimaFeatureSupport.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/SlotFeatureSupport.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/layer/ChainLayerSupport.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/layer/LayerSupport.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/layer/RelationLayerSupport.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/layer/SpanLayerSupport.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/TypeSystemAnalysis.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/WebAnnoCasUtil.java
  webanno-api-annotation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/TypeSystemAnalysisTest.java
  webanno-api-annotation/src/test/resources/3rd-party-tsd/CcpTypeSystem.xml
  webanno-api-annotation/src/test/resources/3rd-party-tsd/README.txt
  webanno-api-annotation/src/test/resources/3rd-party-tsd/creta-typesystem.xml
  webanno-api-annotation/src/test/resources/3rd-party-tsd/ctakes-type-system-4_0.xml
  webanno-api-annotation/src/test/resources/3rd-party-tsd/ttc-term-suite.xml
  webanno-api-annotation/src/test/resources/tsd/chain.xml
  webanno-api-annotation/src/test/resources/tsd/fullMonty.xml
  webanno-api-annotation/src/test/resources/tsd/relationWithPrimitiveFeatures.xml
  webanno-api-annotation/src/test/resources/tsd/spanWithPrimitiveFeatures.xml
  webanno-api-annotation/src/test/resources/tsd/spanWithSlotFeatures.xml
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java
  webanno-io-xmi/pom.xml
  webanno-ui-project/pom.xml
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/LayerDetailForm.java
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.java
  webanno-ui-project/src/main/resources/META-INF/asciidoc/user-guide/projects_layers.adoc
Labels: Module: Import/export, 🐛Bug

#1251 Update installation.adoc
  webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation.adoc
Labels: 🐛Bug, 📖Documentation

#1253 #1252 - Cannot annotate custom layer unless first select existing annotation
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/PreferencesUtil.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationFeatureForm.java
Labels: Module: Annotation, 🐛Bug

#1259 #1257 - Unable to create relation annotations
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
Labels: Module: Annotation, 🐛Bug

#1213 #1212 - Offset for fireRender method of AnnotationEditorExtensionRegistry
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/AnnotationEditorBase.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/AnnotationEditorExtension.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/AnnotationEditorExtensionRegistry.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/AnnotationEditorExtensionRegistryImpl.java
Labels: ⚙️Refactoring

#1264 #1261 - Switch from JCas to CAS
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/RelationAdapter.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter_ImplBase.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/FeatureSupport.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/model/AnnotatorViewState.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/SpanRenderer.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/WebAnnoCasUtil.java
  webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff2.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationFeatureForm.java
  webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/page/AutomationPage.java
  webanno-ui-correction/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/correction/CorrectionPage.java
Labels: ⚙️Refactoring

#1237 #1206 - Better stacking and overlap control
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/RelationOverlapBehavior.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/RelationStackingBehavior.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/SpanOverlapBehavior.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/SpanStackingBehavior.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/TypeSystemAnalysis.java
  webanno-api-annotation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/ChainAdapterTest.java
  webanno-api-annotation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/RelationAdapterTest.java
  webanno-api-annotation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/SpanAdapterTest.java
  webanno-api-annotation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/RelationRendererTest.java
  webanno-api-annotation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/SpanRendererTest.java
  webanno-api-annotation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/TypeSystemAnalysisTest.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/LayerExporter.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/LegacyProjectInitializer.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/initializers/ChunkLayerInitializer.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/initializers/CoreferenceLayerInitializer.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/initializers/DependencyLayerInitializer.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/initializers/LemmaLayerInitializer.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/initializers/MorphologicalFeaturesLayerInitializer.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/initializers/NamedEntityLayerInitializer.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/initializers/OrthographyLayerInitializer.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/initializers/PartOfSpeechLayerInitializer.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/initializers/SemPredArgLayerInitializer.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/initializers/SurfaceFormLayerInitializer.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/initializers/TokenLayerInitializer.java
  webanno-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/LayerExporterTest.java
  webanno-brat/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/message/BratRendererTest.java
  webanno-export/src/main/java/de/tudarmstadt/ukp/clarin/webanno/export/ImportUtil.java
  webanno-model-export/src/main/java/de/tudarmstadt/ukp/clarin/webanno/export/model/ExportedAnnotationLayer.java
  webanno-model/pom.xml
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationLayer.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/OverlapMode.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/OverlapModeType.java
  webanno-model/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/model/db-changelog.xml
  webanno-ui-annotation/src/main/resources/META-INF/asciidoc/user-guide/annotation_create-annotations_span_forward.adoc
  webanno-ui-curation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/util/CopyAnnotationTest.java
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/LayerDetailForm.java
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.html
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.properties
  webanno-ui-project/src/main/resources/META-INF/asciidoc/user-guide/images/layer_details.png
  webanno-ui-project/src/main/resources/META-INF/asciidoc/user-guide/projects_layers.adoc
Labels: Module: Annotation, 🆕Enhancement

#1269 #1268 - Changing the annotation layer in the dropdown field internally changes selectedAnnotationLayer
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationFeatureForm.java
Labels: Module: Annotation, 🐛Bug
