Repository webanno/webanno, pull requests merged in 2020-09, with the labels that each got.

#1760 #1759 User documents view disappear on curation page
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/ClassicKendoComboboxTextFeatureEditor.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureEditor.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/AnnotationPreferencesDialogContent.java
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.java
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratVisualizer.java
  webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/ContextMenu.java
  webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/WicketUtil.java
  webanno-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/ui/ToggleBox.java
  webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/page/AutomationPage.java
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/page/webanno.js
  webanno-ui-correction/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/correction/CorrectionPage.java
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/SuggestionViewPanel.java
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/model/BratSuggestionVisualizer.java
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.html
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.java
Labels: Module: Curation, 🐛Bug

#1769 #1768 - Features of built-in layers should not be deletable
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/FeatureDetailForm.java
  webanno-ui-project/src/main/resources/META-INF/asciidoc/user-guide/projects_layers.adoc
Labels: Module: Settings, 🐛Bug

#1767 #1764 - Error when annotating new layer for the first time
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/ThreadLockingInvocationHandler.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImpl.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasHolder.java
  webanno-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImplTest.java
Labels: 🐛Bug

#1772 #1771 - Curation page does not load
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImpl.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasHolder.java
Labels: Module: Curation, 🐛Bug

#1774 #1773 - Political correctness on user administration page
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/ManageUsersPage.properties
Labels: Module: Settings, 🐛Bug

#1777 #1776 - Unable to use remote API when external authentication is enabled (3.6.x)
  webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/WebAnnoDaoAuthenticationProvider.java
  webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/preauth/ShibbolethRequestHeaderAuthenticationFilter.java
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/ManageUsersPage.java
  webanno-webapp/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/config/WebAnnoSecurity.java
Labels: Module: Remote API, 🐛Bug

#1778 #1776 - Unable to use remote API when external authentication is enabled (master)
  webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/WebAnnoDaoAuthenticationProvider.java
  webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/preauth/ShibbolethRequestHeaderAuthenticationFilter.java
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/ManageUsersPage.java
  webanno-webapp/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/config/WebAnnoSecurity.java
Labels: Module: Remote API, 🐛Bug

#1779 #1770 Adding features to layer should prompt other users to re-open
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/FeatureSupport.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
Labels: 🐛Bug

#1784 #1783 'No layer is selected' when only one layer enabled
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/LayerSelectionPanel.java
Labels: Module: Annotation, 🐛Bug

#1786 #1785 Feature Editor wrongly shown
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/FeatureEditorListPanel.java
Labels: Module: Annotation, 🐛Bug

#1780 Feature/1775 curation cas creation
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CorrectionDocumentServiceImpl.java
  webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/storage/CurationDocumentService.java
  webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/storage/CurationDocumentServiceImpl.java
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/model/SuggestionBuilder.java
Labels: Module: Curation, ⚙️Refactoring

#1766 Feature/1765 clean up constraints grammar file
  webanno-build/src/main/resources/webanno/checkstyle.xml
  webanno-constraints/pom.xml
  webanno-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/ConstraintsServiceImpl.java
  webanno-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/grammar/ASTCondition.java
  webanno-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/grammar/ASTConditions.java
  webanno-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/grammar/ASTConstraintsSet.java
  webanno-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/grammar/ASTQualifiedTypeName.java
  webanno-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/grammar/ASTRestriction.java
  webanno-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/grammar/ASTRestrictions.java
  webanno-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/grammar/ASTRule.java
  webanno-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/model/Condition.java
  webanno-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/model/ParsedConstraints.java
  webanno-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/model/Restriction.java
  webanno-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/model/Rule.java
  webanno-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/parser/ConstraintsParser.java
  webanno-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/visitor/ConditionVisitor.java
  webanno-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/visitor/ImportVisitor.java
  webanno-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/visitor/ParserVisitor.java
  webanno-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/visitor/QuoteUtil.java
  webanno-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/visitor/RestrictionVisitor.java
  webanno-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/visitor/RuleVisitor.java
  webanno-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/visitor/ScopeVisitor.java
  webanno-constraints/src/main/jjtree/ConstraintsGrammar.jjt
  webanno-constraints/src/main/jtb/ConstraintsGrammar.jtb
  webanno-constraints/src/test/java/de/tudarmstadt/ukp/clarin/webanno/constraints/ComplexTypeTest.java
  webanno-constraints/src/test/java/de/tudarmstadt/ukp/clarin/webanno/constraints/ConstraintsParserTest.java
  webanno-constraints/src/test/java/de/tudarmstadt/ukp/clarin/webanno/constraints/SymbolicRulesTest.java
  webanno-constraints/src/test/java/de/tudarmstadt/ukp/clarin/webanno/constraints/eval/ConstraintsGeneratorTest.java
  webanno-constraints/src/test/java/de/tudarmstadt/ukp/clarin/webanno/constraints/eval/ConstraintsVerifierTest.java
  webanno-constraints/src/test/java/de/tudarmstadt/ukp/clarin/webanno/constraints/visitor/ConditionVisitorTest.java
  webanno-constraints/src/test/java/de/tudarmstadt/ukp/clarin/webanno/constraints/visitor/ImportVisitorTest.java
  webanno-constraints/src/test/java/de/tudarmstadt/ukp/clarin/webanno/constraints/visitor/ParserVisitorTest.java
  webanno-constraints/src/test/java/de/tudarmstadt/ukp/clarin/webanno/constraints/visitor/RestrictionVisitorTest.java
  webanno-constraints/src/test/java/de/tudarmstadt/ukp/clarin/webanno/constraints/visitor/RuleVisitorTest.java
  webanno-constraints/src/test/java/de/tudarmstadt/ukp/clarin/webanno/constraints/visitor/ScopeVisitorTest.java
  webanno-constraints/src/test/resources/rules/visitor-test.rules
  webanno-constraints/suppressions.xml
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/constraints/ProjectConstraintsPanel.java
Labels: Module: Constraints, ⚙️Refactoring
