Repository webanno/webanno, pull requests merged in 2020-07, with the labels that each got.

#1728 #1727 Add messages to empty spaces
  webanno-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/coding/PairwiseCodingAgreementTable.html
  webanno-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/coding/PairwiseCodingAgreementTable.java
  webanno-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/unitizing/PairwiseUnitizingAgreementTable.html
  webanno-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/unitizing/PairwiseUnitizingAgreementTable.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/open/OpenDocumentDialogPanel.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/open/OpenDocumentDialogPanel.properties
  webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/OverviewListChoice.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.properties
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.properties
  webanno-ui-monitoring/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/monitoring/page/AgreementPage.java
  webanno-ui-monitoring/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/monitoring/page/AgreementPage.properties
Labels: 🆕Enhancement, 🕶️UX

#1729 #1472 - Upgrade dependencies (4.0.0)
  pom.xml
  webanno-webapp/pom.xml
Labels: ⚙️Refactoring

#1726 #1721 Agreement doesn't work anymore
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImpl.java
  webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/CasStorageService.java
  webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/CasUpgradeMode.java
  webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/casstorage/CasAccessMode.java
  webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff.java
  webanno-ui-monitoring/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/monitoring/page/AgreementPage.java
Labels: Module: Agreement, 🐛Bug

#1730 #1714 - Document does not show after sidebar close
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/AnnotationEditorRenderedMetaDataKey.java
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.java
Labels: Module: Annotation, 🐛Bug

#1725 #1734 add abbreviation marks
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/script/ScriptDirectionActionBarItem.html
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/script/ScriptDirectionActionBarItem.properties
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/guidelines/GuidelinesActionBarItem.html
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/PreferencesActionBarItem.html
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratRenderer.java
  webanno-brat/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/model/LayerNameAbbreviationTest.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/AnnotatorWorkflowActionBarItemGroup.html
Labels: 🆕Enhancement

#1733 #1668 - Upgrade dependencies (3.6.6)
  pom.xml
  webanno-webapp/pom.xml
Labels: ⚙️Refactoring

#1739 #1738 Add getCurrentUsername to UserDao
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/AnnotationPreferencesDialogContent.java
  webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDao.java
  webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/LayerSelectionPanel.java
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/logout/LogoutPanel.java
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/ManageUsersPage.java
Labels: 🆕Enhancement

#1732 #1472 - Upgrade dependencies (4.0.0)
  pom.xml
Labels: ⚙️Refactoring

#1741 #1740 Monitoring paragraph in user guide
  webanno-ui-monitoring/src/main/resources/META-INF/asciidoc/user-guide/agreement.adoc
  webanno-ui-monitoring/src/main/resources/META-INF/asciidoc/user-guide/images/agreement_feature.png
  webanno-ui-monitoring/src/main/resources/META-INF/asciidoc/user-guide/images/agreement_table.png
  webanno-ui-monitoring/src/main/resources/META-INF/asciidoc/user-guide/images/monitoring2.png
  webanno-ui-monitoring/src/main/resources/META-INF/asciidoc/user-guide/images/monitoring3.png
  webanno-ui-monitoring/src/main/resources/META-INF/asciidoc/user-guide/monitoring.adoc
Labels: 📖Documentation

#1737 #1736 Optimize ProjectServiceImpl.listProjectUsersWithPermissions
  webanno-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImplDatabaseTest.java
  webanno-project/pom.xml
  webanno-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
  webanno-project/src/test/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImplTest.java
  webanno-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/AeroRemoteApiControllerTest.java
Labels: ⚙️Refactoring, 🆕Enhancement

#1745 #1744 Issues during Agreement selection
  webanno-ui-monitoring/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/monitoring/page/AgreementPage.java
Labels: Module: Agreement, 🐛Bug
