Repository webanno/webanno, pull requests merged in 2020-03, with the labels that each got.

#1475 #1474 - Dynamic resizing string feature
  pom.xml
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/StringFeatureSupport.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/DynamicTextAreaFeatureEditor.html
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/DynamicTextAreaFeatureEditor.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/DynamicTextAreaScript.js
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/DynamicTextAreaScriptReference.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/StringFeatureTraits.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/StringFeatureTraitsEditor.html
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/StringFeatureTraitsEditor.java
  webanno-ui-annotation/src/main/resources/META-INF/asciidoc/user-guide/annotation_create-annotations_primitive-features.adoc
  webanno-ui-project/src/main/resources/META-INF/asciidoc/user-guide/projects_layers.adoc
Labels: Module: Settings, 🆕Enhancement

#1622 #1620 - Upgrade to most recent embedded Tomcat 8.x
  pom.xml
  webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc
  webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_jar.adoc
  webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings_server.adoc
  webanno-webapp/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/WebAnno.java
Labels: ⚙️Refactoring

#1601 [SECURITY] Use HTTPS to resolve dependencies in Maven Build
  pom.xml
Labels: ⚙️Refactoring

#1618 #1598 annotatorstate metadata
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/model/AnnotatorState.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/model/AnnotatorStateImpl.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/model/AnnotatorStateMetaDataKey.java
Labels: Module: Annotation

#1625 #1624 - Ignore unsupported layers in curation instead of error
  webanno-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/cohenkappa/CohenKappaAgreementMeasure.java
  webanno-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/fleisskappa/FleissKappaAgreementMeasure.java
  webanno-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/krippendorffalpha/KrippendorffAlphaAgreementMeasure.java
  webanno-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/coding/PairwiseCodingAgreementTable.java
  webanno-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/TwoPairedKappaTest.java
  webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff.java
  webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMerge.java
  webanno-curation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiffTest.java
  webanno-curation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMergeSuiteTest.java
  webanno-curation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMergeTest.java
  webanno-curation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMergeTestBase.java
  webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/DescriptionTooltipBehavior.java
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/bootstrap/bootstrap.scss
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/bootstrap/shim-jquery.scss
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/bootstrap/webanno-custom.scss
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/SuggestionViewPanel.java
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/model/SuggestionBuilder.java
Labels: Module: Curation, ⚙️Refactoring

#1631 #1630 - Webanno navbar items do not have fixed height
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/page/MenuBar.html
Labels: 🐛Bug, 🕶️UX

#1627 Bugfix/1623 exporting xmi creates two kinds of document meta data
  webanno-api-annotation/pom.xml
  webanno-api-annotation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/WebAnnoCasUtilTest.java
  webanno-api-dao/pom.xml
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasPersistenceUtils.java
  webanno-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasPersistenceUtilsTest.java
  webanno-diag/pom.xml
  webanno-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/UniqueDocumentAnnotationCheck.java
Labels: 🐛Bug

#1633 #1632 - SASS does not compile on Windows
  webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/sass/UrlImporter.java
Labels: 🐛Bug, 🕶️UX

#1637 Feature/1634 improve performance of project export
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/AnnotationSchemaService.java
  webanno-api-dao/pom.xml
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/ImportExportServiceImpl.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/AnnotationDocumentExporter.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/CuratedDocumentsExporter.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/LayerExporter.java
  webanno-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/ImportExportServiceImplTest.java
  webanno-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/AnnotationDocumentsExporterTest.java
  webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentService.java
  webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/ImportExportService.java
  webanno-io-conll/src/main/java/de/tudarmstadt/ukp/clarin/webanno/conll/Conll2000FormatSupport.java
  webanno-io-conll/src/main/java/de/tudarmstadt/ukp/clarin/webanno/conll/Conll2002FormatSupport.java
  webanno-io-conll/src/main/java/de/tudarmstadt/ukp/clarin/webanno/conll/Conll2003FormatSupport.java
  webanno-io-conll/src/main/java/de/tudarmstadt/ukp/clarin/webanno/conll/Conll2006FormatSupport.java
  webanno-io-conll/src/main/java/de/tudarmstadt/ukp/clarin/webanno/conll/Conll2009FormatSupport.java
  webanno-io-conll/src/main/java/de/tudarmstadt/ukp/clarin/webanno/conll/Conll2012FormatSupport.java
  webanno-io-conll/src/main/java/de/tudarmstadt/ukp/clarin/webanno/conll/ConllCoreNlpFormatSupport.java
  webanno-io-conll/src/main/java/de/tudarmstadt/ukp/clarin/webanno/conll/ConllUFormatSupport.java
  webanno-io-json/src/main/java/de/tudarmstadt/ukp/clarin/webanno/json/JsonFormatSupport.java
  webanno-io-tcf/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tcf/TcfFormatSupport.java
  webanno-io-tei/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tei/TeiFormatSupport.java
  webanno-io-text/src/main/java/de/tudarmstadt/ukp/clarin/webanno/text/LineOrientedTextFormatSupport.java
  webanno-io-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebAnnoTsv1FormatSupport.java
  webanno-io-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebAnnoTsv2FormatSupport.java
  webanno-io-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebAnnoTsv3FormatSupport.java
  webanno-io-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebAnnoTsv3LegacyFormatSupport.java
  webanno-io-xmi/src/main/java/de/tudarmstadt/ukp/clarin/webanno/xmi/XmiFormatSupport.java
Labels: 🆕Enhancement

#1636 #1635 - Guidelines and project log not properly reimported
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/GuildelinesExporter.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/ProjectLogExporter.java
Labels: 🐛Bug

#1639 #1638 - Document Status not displayed properly on Monitoring page
  webanno-ui-monitoring/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/monitoring/page/MonitoringPage.html
Labels: Module: Monitoring, 🐛Bug

#1644 #1643 - Set current project when importing or changing settings
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectImportPanel.java
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/detail/ProjectDetailPanel.java
Labels: 🆕Enhancement

#1642 #1641 - Project import breaks with zip certain files
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/AnnotationDocumentExporter.java
Labels: Module: Import/export, 🐛Bug

#1646 Bugfix/1645 npe when exporting project
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/AnnotationDocumentExporter.java
Labels: Module: Import/export, 🐛Bug

#1650 #1648 Opening the sidebar jumps document back to first page
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
Labels: Module: Annotation, 🐛Bug
