Repository webanno/webanno, pull requests merged in 2020-05, with the labels that each got.

#1670 #1668 - Upgrade dependencies
  pom.xml
Labels: ⚙️Refactoring

#1667 #1472 - Upgrade dependencies
  pom.xml
Labels: ⚙️Refactoring

#1666 #1665 - Replace XML-based Spring Security config with Java-config-based
  webanno-webapp/pom.xml
  webanno-webapp/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/WebAnno.java
  webanno-webapp/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/config/WebAnnoSecurity.java
  webanno-webapp/src/main/resources/META-INF/application-context.xml
  webanno-webapp/src/main/resources/META-INF/preAuthSecurity-context.xml
  webanno-webapp/src/main/resources/META-INF/rest-context.xml
  webanno-webapp/src/main/resources/META-INF/security-context.xml
  webanno-webapp/src/main/resources/META-INF/static-resources-context.xml
Labels: ⚙️Refactoring

#1672 #1472 - Upgrade dependencies
  pom.xml
Labels: ⚙️Refactoring

#1676 #1675 - Update documentation for deployment via systemd
  webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_jar.adoc
Labels: 📖Documentation

#1678 #1677 - Context menus sometimes do not appear
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/bootstrap/webanno-custom.scss
Labels: 🐛Bug

#1682 #1681 - Save time checking for differential update when it will not happen anyway
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.java
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/metrics/BratMetricsImpl.java
Labels: Module: Annotation, ⚙️Refactoring

#1693 #1692 - Adding new tags not possible
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/InputFieldTextFeatureEditor.html
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/keybindings/KeyBindingsPanel.html
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.html
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationFeatureForm.java
Labels: Module: Annotation, 🐛Bug

#1685 #1684 Get some counts from the database
  webanno-api-dao/pom.xml
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/metrics/DocumentsMetrics.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/metrics/DocumentsMetricsImpl.java
  webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentService.java
  webanno-security/pom.xml
  webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDao.java
  webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java
  webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/metrics/UserMetrics.java
  webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/metrics/UserMetricsImpl.java
Labels: ⚙️Refactoring

#1689 #1688 - Modularize action bar
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/ActionBar.html
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/ActionBar.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/ActionBarExtension.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/ActionBarExtensionPoint.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/ActionBarExtensionPointImpl.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/DocumentNavigator.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/docnav/AutoOpenDialogBehavior.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/docnav/DefaultDocumentNavigatorActionBarExtension.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/docnav/DocumentNavigator.html
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/docnav/DocumentNavigator.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/docnav/DocumentNavigator.properties
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/open/OpenDocumentDialog.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/script/ScriptDirectionActionBarExtension.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/FeatureSupport.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/FeatureSupportRegistry.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/FeatureSupportRegistryImpl.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/guidelines/GuidelinesActionBarExtension.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/guidelines/GuidelinesActionBarItem.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/page/AnnotationPageBase.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/paging/PagingActionBarExtension.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/UserPreferencesActionBarExtension.java
  webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/extensionpoint/CachingContextLookupExtensionPoint_ImplBase.java
  webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/extensionpoint/ContextLookupExtensionPoint.java
  webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/extensionpoint/Extension.java
  webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/extensionpoint/ExtensionPoint.java
  webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/extensionpoint/ExtensionPoint_ImplBase.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.html
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotatorWorkflowActionBarItemGroup.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/DefaultWorkflowActionBarExtension.java
  webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/page/AutomationPage.html
  webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/page/AutomationPage.java
  webanno-ui-correction/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/correction/CorrectionPage.html
  webanno-ui-correction/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/correction/CorrectionPage.java
  webanno-ui-correction/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/correction/actionbar/CorrectionWorkflowActionBarExtension.java
  webanno-ui-correction/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/correction/actionbar/CorrectionWorkflowActionBarItemGroup.java
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/actionbar/CurationDocumentNavigatorActionBarExtension.java
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/actionbar/CurationWorkflowActionBarExtension.java
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/actionbar/CuratorWorkflowActionBarItemGroup.html
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/actionbar/CuratorWorkflowActionBarItemGroup.java
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.html
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
Labels: Module: Annotation, ⚙️Refactoring

#1691 Feature/1690 improve speed when importing or deleting large projects
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceEventAdapter.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/ProjectExportServiceImpl.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/AnnotationDocumentExporter.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/SourceDocumentExporter.java
  webanno-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/AnnotationDocumentsExporterTest.java
  webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/ProjectService.java
  webanno-project/pom.xml
  webanno-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
  webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/io/FastIOUtils.java
Labels: Module: Import/export, ⚙️Refactoring

#1680 #1679 - Improve annotation page for smaller screens
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/paging/LineOrientedPagingStrategy.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/paging/SentenceOrientedPagingStrategy.java
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/bootstrap/webanno-actionbar.scss
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/bootstrap/webanno-custom.scss
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/bootstrap/webanno-variables.scss
Labels: Module: Annotation, 🆕Enhancement, 🕶️UX
