Repository webanno/webanno, pull requests merged in 2020-06, with the labels that each got.

#1706 #1668 - Upgrade dependencies (3.6.6)
  pom.xml
Labels: ⚙️Refactoring

#1708 #1707 - Layout for relations not having a label is broken
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/util.js
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer.js
Labels: Module: Annotation, 🐛Bug

#1702 #1700 Option to limit number of users
  webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc
  webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/SettingsUtil.java
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.html
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.java
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.properties
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginProperties.java
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPropertiesImpl.java
  webanno-ui-core/src/main/resources/META-INF/asciidoc/admin-guide/security-login.adoc
Labels: Module: Settings, 🆕Enhancement

#1671 #1669 - Better CAS management
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/AnnotationSchemaService.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/ThreadLockingInvocationHandler.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/WebAnnoCasUtil.java
  webanno-api-dao/pom.xml
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasMetadataUtils.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasPersistenceUtils.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImpl.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/ImportExportServiceImpl.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasHolder.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasKey.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasStorageSession.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/OpenCasStorageSessionForRequestFilter.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/PooledCasHolderFactory.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/SessionManagedCas.java
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/AnnotationDocumentExporter.java
  webanno-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImplTest.java
  webanno-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImplTest.java
  webanno-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/ImportExportServiceImplTest.java
  webanno-api-dao/src/test/resources/log4j2.xml
  webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/CasStorageService.java
  webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentService.java
  webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/casstorage/CasAccessMode.java
  webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/casstorage/CasSessionException.java
  webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/casstorage/WriteAccessNotPermittedException.java
  webanno-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/AeroRemoteApiControllerTest.java
  webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java
  webanno-ui-correction/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/correction/CorrectionPage.java
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/model/SuggestionBuilder.java
  webanno-ui-monitoring/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/monitoring/page/AgreementPage.java
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/casdoctor/ProjectCasDoctorPanel.java
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/FeatureDetailForm.java
  webanno-webapp/src/main/resources/application.properties
Labels: ⚙️Refactoring

#1704 #1703 - Improve brat rendering
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/AnnotationEditorBase.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/AnnotationEditorExtension.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/KendoChoiceDescriptionScriptReference.js
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/AnnotationEditorProperties.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/AnnotationEditorPropertiesImpl.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/UserPreferencesServiceImpl.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/RelationRenderer.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/SpanRenderer.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/model/VObject.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/TypeUtil.java
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.java
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratModelVisualizer.java
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratVisualizer.java
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/message/LoadConfResponse.java
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratRenderer.java
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/model/Entity.java
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/model/EntityAttributes.java
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer.js
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer_ui.js
  webanno-brat/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/display/model/EntityTest.java
  webanno-brat/src/test/resources/output-sentence-oriented.json
  webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/JSONUtil.java
  webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/bootstrap/BootstrapFeedbackPanelJavascriptReference.java
  webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/AjaxComponentRespondListener.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
  webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/page/AutomationPage.java
  webanno-ui-correction/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/correction/CorrectionPage.java
  webanno-ui-curation/pom.xml
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/SuggestionViewPanel.java
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/model/BratSuggestionVisualizer.java
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
  webanno-webapp/src/main/resources/log4j2.xml
Labels: Module: Annotation, 🆕Enhancement, 🕶️UX

#1713 #1712 Auto logout not succeeding
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/logout/LogoutPanel.html
Labels: 🐛Bug

#1715 Feature/1472 upgrade dependencies
  pom.xml
Labels: ⚙️Refactoring

#1698 Feature/access annotation by project name
  webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/WebAnnoConst.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
Labels: 🆕Enhancement
