Repository webanno/webanno, pull requests merged in 2020-12, with the labels that each got.

#1823 #1822 Annotation disabled for curator
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/model/AnnotatorStateImpl.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/page/AnnotationPageBase.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationDocumentStateTransition.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/AnnotatorWorkflowActionBarItemGroup.java
Labels: Module: Curation, 🐛Bug

#1825 #1824 - Update Java version in docker file
  webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_java.adoc
  webanno-webapp/src/main/docker/Dockerfile
  webanno-webapp/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/WebAnno.java
Labels: ⚙️Refactoring

#1832 #1831 - When many tags exist the annotations are not saved
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/KendoAutoCompleteTextFeatureEditor.java
Labels: Module: Annotation, 🐛Bug

#1827 #1826 Update Java JDK in Admin Guide
  webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation.adoc
  webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_database.adoc
  webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_java.adoc
Labels: 📖Documentation

#1837 #1836 - Unable to distinguish between curation and annotation events
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
Labels: Module: Curation, 🐛Bug
