Repository webanno/webanno, pull requests merged in 2021-01, with the labels that each got.

#1839 #1838 - Moving between documents shouldn't throw exceptions
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/docnav/DocumentNavigator.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/model/AnnotatorDocumentNavigation.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/page/AnnotationPageBase.java
Labels: Module: Annotation, ⚙️Refactoring

#1846 #1845 - Move brat-specific settings to brat module
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/AnnotationEditorProperties.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/AnnotationEditorPropertiesImpl.java
  webanno-brat/pom.xml
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.java
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/config/BratAnnotationEditorProperties.java
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/config/BratAnnotationEditorPropertiesImpl.java
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/message/LoadConfResponse.java
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/metrics/BratMetricsImpl.java
  webanno-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings_annotation-editor.adoc
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
  webanno-ui-automation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/automation/page/AutomationPage.java
  webanno-ui-correction/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/correction/CorrectionPage.java
  webanno-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
Labels: Module: Annotation, ⚙️Refactoring

#1844 #1843 - Ready entities for 2nd-level cache support
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnchoringModeType.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationDocumentStateType.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationFeature.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationLayer.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/LinkModeType.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/ModeType.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/MultiValueModeType.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/OverlapModeType.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/PermissionLevelType.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/ProjectPermission.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/ProjectStateType.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/ScriptDirectionType.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/SourceDocumentStateType.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/StatusType.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/TrainDocumentStateType.java
  webanno-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/ValidationModeType.java
  webanno-project/pom.xml
  webanno-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
  webanno-security/pom.xml
  webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java
  webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/model/Authority.java
  webanno-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/model/User.java
  webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/PersistentEnumUserType.java
Labels: ⚙️Refactoring

#1848 #1847 - Detect Docker
  webanno-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/DeploymentMode.java
  webanno-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/TelemetryServiceImpl.java
  webanno-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/ui/TelemetryDetailsPanel.html
Labels: ⚙️Refactoring

#1854 #196 - "typeUiName" in tagset JSON export unnecessary
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/open/OpenDocumentDialogPanel.properties
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/script/ScriptDirectionActionBarItem.properties
  webanno-model-export/src/main/java/de/tudarmstadt/ukp/clarin/webanno/export/model/ExportedTagSet.java
  webanno-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/ProjectTagSetsPanel.java
Labels: 🆕Enhancement

#1857 #1581 - Wicket Ajax error when refreshing settings-page
  webanno-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/WicketUtil.java
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/settings/ProjectSettingsPanelBase.java
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/ImportDocumentsPanel.java
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/guidelines/ImportGuidelinesPanel.java
Labels: Module: Settings, 🐛Bug

#1861 #1860 Redirect to previous url after login does not work
  webanno-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.java
Labels: 🐛Bug

#1864 #1828 - A simple import of already tokenized text to which no further tokenization is applied
  webanno-doc/src/main/resources/META-INF/asciidoc/user-guide/formats-text.adoc
  webanno-io-text/pom.xml
  webanno-io-text/src/main/java/de/tudarmstadt/ukp/clarin/webanno/text/PretokenizedLineOrientedTextReader.java
  webanno-io-text/src/main/java/de/tudarmstadt/ukp/clarin/webanno/text/PretokenizedTextFormatSupport.java
  webanno-io-text/src/test/java/de/tudarmstadt/ukp/clarin/webanno/text/PretokenizedLineOrientedTextReaderTest.java
  webanno-io-text/src/test/resources/text/space-separated-no-final-line-break.txt
  webanno-io-text/src/test/resources/text/text-with-punctuation.txt
Labels: 🆕Enhancement

#1866 #1865 - Annotation details still shown even tough selection has been cleared
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/ClassicKendoComboboxTextFeatureEditor.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/KendoComboboxTextFeatureEditor.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureEditor.java
  webanno-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
Labels: Module: Annotation, 🐛Bug
