Repository webanno/webanno, pull requests merged in 2021-02, with the labels that each got.

#1868 #1867 - Preferences on curation page do not take effect
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/page/AnnotationPageBase.java
Labels: Module: Curation, 🐛Bug

#1870 #1869 - Error during curation if CASes not fully upgraded
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/WebAnnoCasUtil.java
Labels: Module: Curation, 🐛Bug

#1872 #1871 - Repairing CASes does not work
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImpl.java
  webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/CasStorageService.java
  webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/casstorage/CasStorageServiceAction.java
  webanno-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/casstorage/CasStorageServiceLoader.java
  webanno-ui-project/pom.xml
  webanno-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/casdoctor/ProjectCasDoctorPanel.java
Labels: Module: CAS Doctor, 🐛Bug

#1874 #1873 fixed typo
  webanno-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/AgreementUtils.java
  webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff.java
  webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMerge.java
Labels: ⚙️Refactoring

#1876 #1875 - Exception when selecting certain annotations in Firefox
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/annotator_ui.js
Labels: Module: Annotation, browser-firefox, 🐛Bug

#1879 #1878 - Concurrent access protection deletes annotations
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImpl.java
  webanno-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImplTest.java
Labels: Module: Annotation, 🐛Bug

#1881 #1878 - Concurrent access protection deletes annotations
  webanno-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImpl.java
  webanno-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImplTest.java
Labels: Module: Annotation, 🐛Bug

#1882 #1875 - Exception when selecting certain annotations in Firefox
  webanno-brat/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/annotator_ui.js
Labels: Module: Annotation, browser-firefox, 🐛Bug

#1886 #1885 - Cannot merge two relations with the same target
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/FeatureFilter.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/RelationAdapter.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter.java
  webanno-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/WebAnnoCasUtil.java
  webanno-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMerge.java
  webanno-curation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMergeTest.java
Labels: Module: Curation, 🐛Bug
